export const styles = {
    "Monokai Sublime": {
        background: "#23241f",
        normal: "#f8f8f2",
        comment: "#75715e",
        function: "#a6e22e",
        important: "#cb4b16",
        keyword: "#f92672",
        operator: "#f8f8f2",
        property: "#a6e22e",
        punctuation: "#f8f8f2",
        string: "#e6db74",
        tag: "#f8f8f2",
        value: "#ae81ff",
        className: "#f8f8f2",
        boolean: "#ae81ff",
        console: "#e6db74",
        builtin: "#e6db74",
        variable: "#e6db74",
    },
    Dracula: {
        background: "#282a36",
        normal: "#f8f8f2",
        comment: "#6272a4",
        function: "#50fa7b",
        important: "#ffb86c",
        keyword: "#ff79c6",
        operator: "#f8f8f2",
        property: "#8be9fd",
        punctuation: "#f8f8f2",
        string: "#f1fa8c",
        tag: "#bd93f9",
        value: "#bd93f9",
        className: "#f8f8f2",
        boolean: "#bd93f9",
        console: "#f1fa8c",
        builtin: "#8be9fd",
        variable: "#f8f8f2",
    },
    "GitHub Dark": {
        background: "#0d1117",
        normal: "#E6EDF3",
        comment: "#8B949E",
        function: "#d2a8ff",
        important: "#ff7b72",
        keyword: "#FF7B72",
        operator: "#79C0FF",
        property: "#79C0FF",
        punctuation: "#E6EDF3",
        string: "#a5d6ff",
        tag: "#7ee787",
        value: "#79C0FF",
        className: "#ffa657",
        boolean: "#7ee787",
        console: "#c9d1d9",
        builtin: "#a5d6ff",
        variable: "#a5d6ff",
    },
};