export const styles = {
    "Monokai Sublime": {
        background: "#23241f",
        normal: "#f8f8f2",
        comment: "#75715e",
        function: "#a6e22e",
        important: "#cb4b16",
        keyword: "#f92672",
        operator: "#f8f8f2",
        property: "#a6e22e",
        punctuation: "#f8f8f2",
        string: "#e6db74",
        tag: "#f8f8f2",
        value: "#ae81ff",
        className: "#f8f8f2",
        boolean: "#ae81ff",
        console: "#e6db74",
        builtin: "#e6db74",
        variable: "#e6db74",
    },
    Dracula: {
        background: "#282a36",
        normal: "#f8f8f2",
        comment: "#6272a4",
        function: "#50fa7b",
        important: "#ffb86c",
        keyword: "#ff79c6",
        operator: "#f8f8f2",
        property: "#8be9fd",
        punctuation: "#f8f8f2",
        string: "#f1fa8c",
        tag: "#bd93f9",
        value: "#bd93f9",
        className: "#f8f8f2",
        boolean: "#bd93f9",
        console: "#f1fa8c",
        builtin: "#8be9fd",
        variable: "#f8f8f2",
    },
    "GitHub Dark": {
        background: "#0d1117",
        normal: "#E6EDF3",
        comment: "#8B949E",
        function: "#d2a8ff",
        important: "#ff7b72",
        keyword: "#FF7B72",
        operator: "#79C0FF",
        property: "#79C0FF",
        punctuation: "#E6EDF3",
        string: "#a5d6ff",
        tag: "#7ee787",
        value: "#79C0FF",
        className: "#ffa657",
        boolean: "#7ee787",
        console: "#c9d1d9",
        builtin: "#a5d6ff",
        variable: "#a5d6ff",
    },
    "Tokyo Night Dark": {
        background: "#1a1b26",
        normal: "#9aa5ce",
        comment: "#51597d",
        function: "#ffcc66",
        important: "#ff6e6e",
        keyword: "#bb9af7",
        operator: "#9aa5ce",
        property: "#78dce8",
        punctuation: "#9aa5ce",
        string: "#a9dc76",
        tag: "#f7768e",
        value: "#ff9e64",
        console: "#f7768e",
        builtin: "#7dcfff",
        variable: "#9aa5ce",
    },
    "Tomorrow Night Bright": {
        background: "#0d1117",
        normal: "#cccccc",
        comment: "#969896",
        function: "#e78c45",
        important: "#ff6666",
        keyword: "#cc99cc",
        operator: "#cccccc",
        property: "#99cccc",
        punctuation: "#cccccc",
        string: "#b9ca4a",
        tag: "#cc99cc",
        value: "#e78c45",
        console: "#d54e53",
        builtin: "#7aa6da",
        variable: "#cccccc",
    },
    "Atom One Dark": {
        background: "#282c34",
        normal: "#abb2bf",
        comment: "#5c6370",
        function: "#61aeee",
        important: "#e06c75",
        keyword: "#c678dd",
        operator: "#abb2bf",
        property: "#98c379",
        punctuation: "#abb2bf",
        string: "#98c379",
        tag: "#c678dd",
        value: "#d19a66",
        variable: "#abb2bf",
    },
};
